install.packages("nnet")
install.packages("caret")
library(nnet)   
library(caret)  
"nnet" %in% rownames(installed.packages())
"caret" %in% rownames(installed.packages())
library(nnet)   
library(caret)  
data("iris")
set.seed(123) 
sample_index <- sample(1:nrow(iris), 0.8 * nrow(iris))
train_data <- iris[sample_index, ]
test_data  <- iris[-sample_index, ]
model <- multinom(Species ~ Petal.Length + Petal.Width, data=train_data)
pred_probs <- predict(model, newdata=test_data[, c("Petal.Length", "Petal.Width")], type="prob")
pred_class <- predict(model, newdata=test_data[, c("Petal.Length", "Petal.Width")])
conf_matrix <- confusionMatrix(pred_class, test_data$Species)
cat("Predicted probabilities (first 6 rows):\n")
print(head(pred_probs))
cat("\nConfusion Matrix:\n")
print(conf_matrix)
