set.seed(123)  
rand_nums <- rnorm(20, mean = 0, sd = 1)  
rand_nums_rounded <- round(rand_nums, 2)
rand_list <- as.list(rand_nums_rounded)
occurrences <- table(rand_nums_rounded)
print("Random numbers in normal distribution:")
print(rand_list)
print("Occurrences of each value:")
print(occurrences)
