data("iris")
print("First 6 rows of iris dataset:")
head(iris)
print("Structure of iris dataset:")
str(iris)
print("Summary statistics:")
summary(iris)
cat("Number of Rows:", nrow(iris), "\n")
cat("Number of Columns:", ncol(iris), "\n")
cat("Any missing values? ", any(is.na(iris)), "\n")
print("Distribution of Species:")
table(iris$Species)
print("Correlation matrix:")
print(cor(iris[,1:4]))
par(mfrow=c(2,2))  # arrange plots
boxplot(Sepal.Length ~ Species, data=iris, main="Sepal Length by Species", col="lightblue")
boxplot(Sepal.Width  ~ Species, data=iris, main="Sepal Width by Species", col="lightgreen")
boxplot(Petal.Length ~ Species, data=iris, main="Petal Length by Species", col="lightpink")
boxplot(Petal.Width  ~ Species, data=iris, main="Petal Width by Species", col="lightyellow")
pairs(iris[,1:4], col=iris$Species, main="Scatterplot Matrix of Iris Dataset")
print("Mean values by Species:")
aggregate(. ~ Species, data=iris, FUN=mean)
